### ISSUE TITLE
能否设置调用手机浏览器下载呢

### ISSUE THREAD

**Issue by Theodore-98** [jing332/AlistAndroid#12]
最新版内置网页，但是没办法直接下载，只能复制链接到浏览器下载，下载多个文件的时候很麻烦

**Comment by Theodore-98** [comment]
> 最新版内置网页，但是没办法直接下载，只能复制链接到浏览器下载

下载多个文件的时候很麻烦

**Comment by jing332** [comment]
@Theodore-98 后续会完善，批量下载推荐用 发送到aria2，配合aria2android使用。
https://github.com/devgianlu/Aria2Android

**Comment by jing332** [comment]
已更新，可以先在 [Action](https://github.com/jing332/AlistAndroid/actions) 下载

**Comment by Theodore-98** [comment]
> 已更新，可以先在 [Action](https://github.com/jing332/AlistAndroid/actions) 下载

不好意思，刚才试了一下，还是没有调用手机浏览器下载https://github.com/jing332/AlistAndroid/assets/90173843/c17d0bdb-4ab8-47ce-b84c-2ae8b58241cd

**Comment by Theodore-98** [comment]
> 已更新，可以先在 [Action](https://github.com/jing332/AlistAndroid/actions) 下载

不好意思，刚才试了一下，还是没有调用浏览器下载![Image-17-03-49.gif](https://github.com/jing332/AlistAndroid/assets/90173843/8fb9537a-6ba6-4883-a31e-9ccf5f68abbc)

**Comment by jing332** [comment]
> > 已更新，可以先在 [Action](https://github.com/jing332/AlistAndroid/actions) 下载
> 
> 不好意思，刚才试了一下，还是没有调用浏览器下载![Image-17-03-49.gif](https://github.com/jing332/AlistAndroid/assets/90173843/8fb9537a-6ba6-4883-a31e-9ccf5f68abbc)
> 
> 

在Actions下载，这个版本我还没release呢

**Comment by jing332** [comment]
emmm，用系统下载器，文件的名称有些问题🙄

**Comment by Theodore-98** [comment]
> > > 已更新，可以先在 [Action](https://github.com/jing332/AlistAndroid/actions) 下载
> > 
> > 不好意思，刚才试了一下，还是没有调用浏览器下载![Image-17-03-49.gif](https://github.com/jing332/AlistAndroid/assets/90173843/8fb9537a-6ba6-4883-a31e-9ccf5f68abbc)
> > 
> > 
> 
> 在Actions下载，这个版本我还没release呢

可以下载了，感谢大佬👍🏻👍🏻👍🏻
