### ISSUE TITLE
没必要每次打开都跳转到电池优化界面吧

### ISSUE THREAD

**Issue by pheotry** [jing332/AlistAndroid#2]
第一次安装的时候可以跳转一下，后面就没必要了吧

**Comment by jing332** [comment]
> 跳转条件是未加到白名单

所以只要授予了优化白名单，那就不会跳了

**Comment by pheotry** [comment]
> > 跳转条件是未加到白名单
> 
> 所以只要授予了优化白名单，那就不会跳了

问题就是不想给白名单啊，还是改成第一次启动提示开启比较好，后面不管关没关电池优化都没必要跳转

**Comment by jing332** [comment]
@pheotry 你不给电池白名单怎么在后台用？
若是Android后台一限制，你网页就无法访问了。

**Comment by pheotry** [comment]
> @pheotry 你不给电池白名单怎么在后台用？ 若是Android后台一限制，你网页就无法访问了。

电池优化只是保持不杀后台啊，问题是你都常驻通知了，常驻通知也不会杀后台啊。
另外平常基本用的都是电脑alist，只有不用电脑的时候才会用手机啊。

最后，我只是说头次打开的时候提示让关掉电池优化，这也是大多数这类软件的操作逻辑啊，而不是不关的话每次打开软件都弹出来

**Comment by jing332** [comment]
尽管设为了前台服务，但国内系统千奇百样，搞不好各种魔改。
你的建议我会采纳，不过目前抽不开精力开发，见谅。

**Comment by pheotry** [comment]
> 尽管设为了前台服务，但国内系统千奇百样，搞不好各种魔改。 你的建议我会采纳，不过目前抽不开精力开发，见谅。

好的
