### ISSUE TITLE
Github actions是失效了吗？ Alist已经发布了3.27版本 但是这边并没有同步更新

### ISSUE THREAD

**Issue by haohaohaoadsad** [jing332/AlistAndroid#5]

**Comment by haohaohaoadsad** [comment]
我FORK了作者的仓库并且完成了编译发布
https://github.com/haohaohaoadsad/AlistAndroid
希望作者早日回来修一下
由于没有作者的签名，只能换一个签名了。。

**Comment by jing332** [comment]
之前出了些问题，所以我把就Action禁用了。现在应该可以了。

**Comment by haohaohaoadsad** [comment]
> 之前出了些问题，所以我把就Action禁用了。现在应该可以了。

https://github.com/jing332/AlistAndroid/actions/runs/6393371623/job/17352466856
release失败了

**Comment by ypq123456789** [comment]
> 之前出了些问题，所以我把就Action禁用了。现在应该可以了。

哥 现在还是没更新

**Comment by thesexday** [comment]
没法更新

**Comment by thesexday** [comment]
求更新3.29.1
