### ISSUE TITLE
红米手机使用时的一个bug

### ISSUE THREAD

**Issue by kukudelang** [jing332/AlistAndroid#6]
无法获取手机存储的读写权限，导致挂载本地存储空间时只能看到文件夹名字无法看到里面的内容，MIUI14系统

**Comment by firgk** [comment]
别再软件的设置中选择权限，而是在系统的权限中打开储存权限，（遇到了一样的问题，我已经试过了，可行），可能是因为软件开发者，没有设置第一次运行的时候获取储存权限。

**Comment by free-150** [comment]
确实有这个问题，在系统的权限中没有打开储存权限这一选项。希望作者能解决下。

**Comment by jing332** [comment]
系统设置中打开 `特殊权限 -> 所有文件访问权限 -> AList -> 授予管理所有文件的权限` 即可解决
后续我会更新，快捷调转到此授权界面。
