### ISSUE TITLE
有没有办法实现开机就启动alist呢？

### ISSUE THREAD

**Issue by mrd-mrd** [jing332/AlistAndroid#7]
有没有办法实现开机就启动alist呢

**Comment by mrd-mrd** [comment]
有没有办法实现开机就启动alist呢

**Comment by jing332** [comment]
已加入开机自启动设置

**Comment by valetzx** [comment]
打开自启开关似乎没用，是要另外给什么权限吗，不是重启自动后台开alist服务的效果，系统版本 `安卓7.1.2` 软件版本 `AList-v1.24.011220_arm64-v8a`
