### ISSUE TITLE
已发布新版1.23.100.122,内部AList版本为3.28.0

### ISSUE THREAD

**Issue by xx6z8v** [jing332/AlistAndroid#8]
下载地址：https://lanzouy.com/tp/i07ED1eldlmd
说明：其他人基于原作者的代码更新的，签名不一样，卸载原版后才能安装

**Comment by thesexday** [comment]
能不能更新到3.29.1

**Comment by ypq123456789** [comment]
方便问下来源是啥吗，也好追更新
