### ISSUE TITLE
求大佬更新3.29.1版

### ISSUE THREAD

**Issue by thesexday** [jing332/AlistAndroid#9]
求大佬更新3.29.1版，多谢！

**Comment by idkcckdk** [comment]
已经落后几个版本，是不是无心更新了。

**Comment by jing332** [comment]
@idkcckdk 抱歉了，我目前没有精力开发维护下去了，见谅。

**Comment by weigui404** [comment]
3.29.1，有一些bug。
https://github.com/weigui404/AlistAndroid/releases/tag/1.23.121218

**Comment by thesexday** [comment]
> 3.29.1，有一些bug。 https://github.com/weigui404/AlistAndroid/releases/tag/1.23.121218

多谢大佬！

**Comment by jing332** [comment]
已更新
